# Generated by Django 5.2.4 on 2025-07-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('ultrasound_type', models.CharField(max_length=100)),
                ('findings', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasoundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultrasound_type', models.CharField(default='Abdominal Ultrasound', max_length=100)),
                ('reason', models.TextField(default='Routine check-up')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('requester', models.CharField(default='Dr. Felix', max_length=100)),
                ('requester_role', models.CharField(blank=True, max_length=50, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient_register')),
                ('ultrasound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiology.ultrasound')),
            ],
        ),
    ]
