# Generated by Django 5.2.3 on 2025-06-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_appointment_created_by"),
        ("radiology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ultrasound",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.CreateModel(
            name="UltrasoundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient_register",
                    ),
                ),
                (
                    "ultrasound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="radiology.ultrasound",
                    ),
                ),
            ],
        ),
    ]
