# Generated by Django 5.2.3 on 2025-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiology", "0002_alter_ultrasound_image_ultrasoundrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ultrasoundrequest",
            old_name="requested_at",
            new_name="request_date",
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("routine", "Routine"),
                    ("urgent", "Urgent"),
                    ("emergency", "Emergency"),
                ],
                default="routine",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="reason",
            field=models.TextField(default="Routine check-up"),
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="requester",
            field=models.CharField(default="Dr. Felix", max_length=100),
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="requester_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="ultrasoundrequest",
            name="ultrasound_type",
            field=models.CharField(default="Abdominal Ultrasound", max_length=100),
        ),
    ]
