# Generated by Django 5.2.3 on 2025-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "radiology",
            "0003_rename_requested_at_ultrasoundrequest_request_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ultrasound",
            name="price",
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
