# Generated by Django 5.2.4 on 2025-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_billing_due_date_billing_is_overdue_billing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='receipt_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
