# Generated by Django 5.2.4 on 2025-07-14 11:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_billing_receipt_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.RemoveField(
            model_name='billing',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='billing',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient_register'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card Payment'), ('insurance', 'Insurance'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
