# Generated by Django 5.2 on 2025-04-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_register_discharge_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("diagnosis", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                ("doctor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient_register",
                    ),
                ),
            ],
        ),
    ]
