# Generated by Django 5.2.4 on 2025-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_paymenthistory_options_remove_billing_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_register',
            name='status',
            field=models.CharField(default='Admitted', max_length=50),
        ),
    ]
