# Generated by Django 5.2 on 2025-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patienthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_register",
            name="ward",
            field=models.CharField(default="General Ward", max_length=100),
        ),
    ]
