# Generated by Django 5.2.4 on 2025-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_register',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
