# Generated by Django 5.2.3 on 2025-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_appointment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_register',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='ward',
            field=models.CharField(default='Outpatient', max_length=100),
        ),
    ]
