# Generated by Django 5.2.3 on 2025-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_register_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_register',
            name='ward',
            field=models.CharField(default='OPD', max_length=100),
        ),
    ]
