# Generated by Django 5.2.4 on 2025-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_register_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='hpi',
            field=models.TextField(blank=True, verbose_name='History of Present Illness'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='signs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalized')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
