# Generated by Django 5.2.4 on 2025-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patienthistory_blood_pressure_patienthistory_hpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_register',
            name='residence',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
