# Generated by Django 5.2.4 on 2025-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugissue',
            name='given',
            field=models.BooleanField(default=False),
        ),
    ]
