# Generated by Django 5.2.4 on 2025-07-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_otcsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otcsale',
            options={'ordering': ['-sale_datetime'], 'verbose_name': 'OTC Sale', 'verbose_name_plural': 'OTC Sales'},
        ),
        migrations.AlterField(
            model_name='otcsale',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Cashier/User who processed the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otcsale',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Customer Contact (optional)'),
        ),
        migrations.AlterField(
            model_name='otcsale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer Name (optional)'),
        ),
    ]
