# Generated by Django 5.2.4 on 2025-07-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_otcsale_options_alter_otcsale_cashier_and_more'),
        ('patients', '0006_patient_register_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugissue',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_issues_for_bill', to='patients.billing'),
        ),
    ]
