# Generated by Django 5.2.4 on 2025-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_prescriptionitem_is_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
