# Generated by Django 5.2.4 on 2025-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_alter_prescriptionitem_is_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='is_fulfilled',
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
