# Generated by Django 5.2 on 2025-05-01 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0005_patient_register_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labaratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labaratory_name", models.CharField(max_length=100)),
                ("labaratory_location", models.CharField(max_length=100)),
                ("labaratory_description", models.TextField(blank=True)),
                ("labaratory_phone", models.CharField(blank=True, max_length=20)),
                ("labaratory_email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="LabaratoryAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("appointment_reason", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labaratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labaratory.labaratory",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient_register",
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="LabaratoryTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("test_description", models.TextField()),
                ("test_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("test_duration", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labaratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labaratory.labaratory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabaratoryTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_result", models.TextField()),
                ("test_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "labaratory_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labaratory.labaratorytest",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient_register",
                    ),
                ),
            ],
        ),
    ]
