# Generated by Django 5.2 on 2025-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labaratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labaratorytest",
            options={"ordering": ["test_name"]},
        ),
        migrations.AddField(
            model_name="labaratorytest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
