# Generated by Django 5.2 on 2025-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labaratory", "0002_alter_labaratorytest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labaratorytestresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
