# Generated by Django 5.2.3 on 2025-06-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labaratory", "0003_labaratorytestresult_status"),
        ("patients", "0008_appointment_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory_requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "labaratory_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labaratory.labaratorytest",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient_register",
                    ),
                ),
            ],
        ),
    ]
